spring:
  application:
    name: demoservice
server:
  port: 8080

---
spring:
  profiles: dev
  application:
    name: demoservice
server:
  port: 9000
debug: true

message:
  welcome: Welcome to the configuration server xx
---
spring:
  profiles: prod
  application:
    name: demoservice
server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: bfmzevdn
    key-store-type: PKCS12
    key-alias: tomcat

